## 라이브러리 불러오기

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

## 데이터셋 만들기

In [2]:
col = ['장르', '재미있는', '연인', '사랑', '맹렬한', '빠른', '총격', '날으는']

genre = ['코미디', '액션', '코미디', '액션', '액션']
V1 = [1, 0, 2, 1, 0]
V2 = [1, 0, 1, 0, 0]
V3 = [2, 0, 0, 0, 1]
V4 = [0, 1, 0, 1, 0]
V5 = [0, 1, 1, 0, 1]
V6 = [0, 1, 0, 2, 1]
V7 = [0, 0, 1, 0, 1]

dic = {'장르':genre, 'V1':V1, 'V2':V2, 'V3':V3, 'V4':V4, 'V5':V5, 'V6':V6, 'V7':V7}

In [3]:
dic

{'장르': ['코미디', '액션', '코미디', '액션', '액션'],
 'V1': [1, 0, 2, 1, 0],
 'V2': [1, 0, 1, 0, 0],
 'V3': [2, 0, 0, 0, 1],
 'V4': [0, 1, 0, 1, 0],
 'V5': [0, 1, 1, 0, 1],
 'V6': [0, 1, 0, 2, 1],
 'V7': [0, 0, 1, 0, 1]}

In [6]:
dic2 = pd.DataFrame(dic)
dic2.columns = col

In [8]:
dic2.columns

Index(['장르', '재미있는', '연인', '사랑', '맹렬한', '빠른', '총격', '날으는'], dtype='object')

In [7]:
dic2

장르  재미있는  연인  사랑  맹렬한  빠른  총격  날으는
0  코미디     1   1   2    0   0   0    0
1   액션     0   0   0    1   1   1    0
2  코미디     2   1   0    0   1   0    1
3   액션     1   0   0    1   0   2    0
4   액션     0   0   1    0   1   1    1

## 0보다 큰 경우 'yes'로 반환하는 사용자 정의 함수를 생성

In [14]:
def convert(x):
    if x>0:
        return 1
    else:
        return 0
# convert(1) -> yes
# convert(0) -> 'no'

In [10]:
convert(1)

'yes'

In [11]:
convert(0)

'no'

In [15]:
dic2['재미있는'].apply(convert)

0    1
1    0
2    1
3    1
4    0
Name: 재미있는, dtype: int64

In [16]:
dic2.columns[1:]

Index(['재미있는', '연인', '사랑', '맹렬한', '빠른', '총격', '날으는'], dtype='object')

In [17]:
for x in dic2.columns[1:]: dic2[x]=dic2[x].apply(convert)

In [18]:
dic2

장르  재미있는  연인  사랑  맹렬한  빠른  총격  날으는
0  코미디     1   1   1    0   0   0    0
1   액션     0   0   0    1   1   1    0
2  코미디     1   1   0    0   1   0    1
3   액션     1   0   0    1   0   1    0
4   액션     0   0   1    0   1   1    1

#### 가능하면 list comprehension, apply를 쓸 것 for문은 최대한 자제

#### R에서는 문자를 factor로 바꿔주면 들어가는데
#### python에서는 숫자가 아니면 안들어감 ... 면접 때 알고리즘 설명 가능해야

#### 정규분포를 따르는 경우는 거의 없음, 대부분 multinomial Naive Bayes (다항분포)

In [ ]:
## in gaussian ... 
## parameter : 사전 확률, 매우 작은 수만큼 추가 가능 
## attribute : 모델을 만들고 . 뒤에 각 class에서 관찰된 횟수 추가 가능

## 나이브베이즈 모델 적용(Laplace 적용x)

In [22]:
from sklearn.naive_bayes import MultinomialNB

# alpha : laplace 추정기, default 1
# class_prior : 사전확률 직접 정의 
# 사전 확률 : 구분하고 싶은 최종 확률
## comedy가 5개중 2개, action이 5개중 3개 -> 어떤 단어 B를 뽑았을 때 A인 경우
## 사전 확률을 곱해줘서 사전 확률에 따른 그 단어의 확률을 구함 (사후 확률)
# fit_prior : 사전확률 적합, default True

model = MultinomialNB(alpha=0)
model.fit(dic2.iloc[:, 1:], dic2['장르']) # dic2.iloc : 숫자로 데이터 프레임의 행렬 접근, 장르 : 알고 싶은 것

C:\anaconda\lib\site-packages\sklearn\naive_bayes.py:512: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


MultinomialNB(alpha=0)

### attribute

In [21]:
# alpha : alpha값 확인
model.alpha

0

In [23]:
# classes_ : 클래스 이름
# 학습 시켜준 이후에
model.classes_

array(['액션', '코미디'], dtype='<U3')

In [25]:
# class_count_ : 클래스 개수 반환
model.class_count_
# action 3 comedy 2 exist

array([3., 2.])

In [26]:
# feature_count_ : 각 클래스별 단어 개수 등장 횟수
model.feature_count_ # 위에껀 action에서 나타나는 단어 개수, 아래껀 comedy에서 나타나는 단어 개수

array([[1., 0., 1., 2., 2., 3., 1.],
       [2., 2., 1., 0., 1., 0., 1.]])

In [28]:
# class_log_prior_ : class별 log를 씌운 사전확률
# log_e_1.33 에 e를 씌우면 1.33
# 수학적 모듈 np
np.exp(model.class_log_prior_)

array([0.6, 0.4])

In [29]:
# feature_log_prob_ : 단어별 log를 씌운 사후확률
np.exp(model.feature_log_prob_)

array([[1.00000000e-01, 1.00000000e-11, 1.00000000e-01, 2.00000000e-01,
        2.00000000e-01, 3.00000000e-01, 1.00000000e-01],
       [2.85714286e-01, 2.85714286e-01, 1.42857143e-01, 1.42857143e-11,
        1.42857143e-01, 1.42857143e-11, 1.42857143e-01]])

## '재미있는 맹렬한 빠른' 단어가 나올경우

In [30]:
dic2.columns

Index(['장르', '재미있는', '연인', '사랑', '맹렬한', '빠른', '총격', '날으는'], dtype='object')

In [36]:
# test set 만들기
test = np.array([1, 0, 0, 1, 1, 0, 0])#reshape(1,-1) # 재미있는 맹렬한 빠른
# 머신러닝에서는 list말고 array로 넣을 것
# (-1,1) : 행을 1열로 하라 -> 7행

In [37]:
test.shape

(7,)

In [40]:
test = np.array([1, 0, 0, 1, 1, 0, 0]).reshape(1,-1)
test # 대괄호 2개

array([[1, 0, 0, 1, 1, 0, 0]])

In [41]:
# 예측
model.predict(test)
# reshape (차원 변경)하라 -> (1, -1)

array(['액션'], dtype='<U3')

In [42]:
# 확률 확인
model.predict_proba(test)
# 거의 1에 가까움 -> action

array([[1.00000000e+00, 9.71817298e-11]])

## 나이브베이즈 모델 적용(Laplace 적용o)

In [43]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB(alpha=1)
model.fit(dic2.iloc[:, 1:], dic2['장르'])


MultinomialNB(alpha=1)

In [44]:
# 예측
model.predict(test)

array(['액션'], dtype='<U3')

In [45]:
# 확률 확인
model.predict_proba(test)
# 확률이 좀 낮아짐 - 학습이 극단적이면 안됨

array([[0.71536991, 0.28463009]])

## 데이터 불러오기

In [47]:
wine = pd.read_csv("./input/wine.csv")

wine['grade'] = ['Good' if x in range(3,7) else 'Best' for x in wine['quality']]

x_data = wine.drop(['quality', 'grade'], axis=1)
y_data = wine['grade']

from sklearn.preprocessing import StandardScaler

# scaler 생성
standard_scaler = StandardScaler()

# scaler 학습
standard_scaler.fit(x_data)

# scaler 적용
wine_scaled = standard_scaler.transform(x_data)

# 최종 데이터프레임 만들기
x_data = pd.DataFrame(wine_scaled, columns=x_data.columns)


from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.2, random_state = 321)

In [48]:
col = ['장르', '재미있는', '연인', '사랑', '맹렬한', '빠른', '총격', '날으는']

genre = ['코미디', '액션', '코미디', '액션', '액션']
V1 = [1, 0, 2, 1, 0]
V2 = [1, 0, 1, 0, 0]
V3 = [2, 0, 0, 0, 1]
V4 = [0, 1, 0, 1, 0]
V5 = [0, 1, 1, 0, 1]
V6 = [0, 1, 0, 2, 1]
V7 = [0, 0, 1, 0, 1]

dic = {'장르':genre, 'V1':V1, 'V2':V2, 'V3':V3, 'V4':V4, 'V5':V5, 'V6':V6, 'V7':V7}


data = pd.DataFrame(dic)
data.columns = col


def convert(x):
    if x > 0:
        return 1
    else:
        return 0
    

for i in data.columns[1:]:
    data[i] = data[i].apply(convert)

In [56]:
data=pd.read_csv('./input/HouseVotes84.csv')

## 결측치 채우기

In [57]:
# 결측치가 있는 행만 불러오기
temp = data.isna().sum(axis=1)
len(temp[temp!=0].index)

202

In [58]:
data.fillna('y', inplace=True)

## n이면 0, y면 1 적용

In [64]:
def convert(x):
    if x == 'n':
        return 0
    else:
        return 1

In [65]:
for i in data.columns[1:]:
    data[i]=data[i].apply(convert)

In [66]:
data

Class  V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11  V12  V13  V14  \
0    republican   0   1   0   1   1   1   0   0   0    1    1    1    1    1   
1    republican   0   1   0   1   1   1   0   0   0    0    0    1    1    1   
2      democrat   1   1   1   1   1   1   0   0   0    0    1    0    1    1   
3      democrat   0   1   1   0   1   1   0   0   0    0    1    0    1    0   
4      democrat   1   1   1   0   1   1   0   0   0    0    1    1    1    1   
..          ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...   
429  republican   0   0   1   1   1   1   0   0   1    1    0    1    1    1   
430    democrat   0   0   1   0   0   0   1   1   1    1    0    0    0    0   
431  republican   0   1   0   1   1   1   0   0   0    0    1    1    1    1   
432  republican   0   0   0   1   1   1   1   1   1    1    0    1    1    1   
433  republican   0   1   0   1   1   1   0   0   0    1    0    1    1    1   

     V15  V16  
0      0    1  
1      0    1  
2      0    0  
3      0    1  
4      1    1  
..   ...  ...  
429    0    1  
430    0    1  
431    0    1  
432    0    1  
433    1    0  

[434 rows x 17 columns]

## train test 분리

In [ ]:
import random

# random seed 설정하기




In [ ]:
x_data=data.iloc[:, 1:] # 2번째 column부터 끝까지
y_data=data['Class'] # 종속변수

In [ ]:
from sklearn.model_selection import train_test_split
# train, test set분리
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=7) 
# 100개 중에 30개를 뽑는데 seed 값에 따라 뽑히는 값이 다름

## 나이브베이즈 모델 적용

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB(alpha=1)
model.fit(X_train, y_train)

In [ ]:
# test 데이터로 예측
model.predict(X_test)

In [ ]:
# 정확도 확인
sum(y_pred==y_test)/len(y_test)

In [ ]:
# random forest ... decision tree가 주알고리즘