In [27]:
import numpy as np # linear algebra
#import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
#import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [3]:
from numpy import genfromtxt
X = genfromtxt('./data/X_multi.csv', delimiter=',',skip_header=1)
y = genfromtxt('./data/y_multi.csv', delimiter=',',skip_header=1) # class

In [4]:
y.shape # numpy.ndarray

(944,)

In [5]:
X.shape

(944, 3)

In [6]:
yy = y.astype(int) # 형변환 float-> int
yy[0]

2

In [7]:
# one-hot encoding
y_onehot = np.zeros((yy.size, yy.max()+1)) 
y_onehot[np.arange(yy.size),yy] = 1 # Frankly speaking, I am not understanding this command.

In [8]:
y_onehot

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [9]:
XX = X[:, 1:3] # explanatory v ... column 1,2
XX.shape

(944, 2)

In [11]:
# logistic regression - estimation result
softReg = LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs')
# solve option : machine to optimize problem
# standard ... one-hot encoding

softReg.fit(XX,yy) # yy is not one-hot encoded!!!! # providing data
# one-hot encoding y 넣으면 error

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [23]:
softReg = LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs')
softReg.fit(XX,yy) 
# poisson ... 이랑 다르게 intercept (1로 채워진 0열) 필요로 하지 않음

LogisticRegression(multi_class='multinomial')

In [24]:
softReg.intercept_

array([ 0.78064075, -0.406528  , -0.37411275])

In [25]:
softReg.coef_ # interpret
# class가 0, 1, 2 3개인데 두 개로 classify해버리면 정확도가 0.5도 채 안됨
# 1행 : cat, 2행 : dog, 3행 : other

array([[-0.00145259, -0.01133095],
       [-0.00122703,  0.00479373],
       [ 0.00267962,  0.00653722]])

Q1 : Calculate $(P_0^{[0]}, P_1^{[0]}, P_2^{[0]})$

Q2 : What is your prediction of the 0-th person?

In [13]:
X[0,:] # Calculate the probabilities -> p_0

array([ 1. , 36. ,  1.5])

In [14]:
coeffs = softReg.intercept_

In [15]:
# 각각 cat, dog, other
# intercept + model matrix (parameter(coef))
Z0 = coeffs[0] + np.dot(XX, softReg.coef_[0, :].T) # transpose
Z1 = coeffs[1] + np.dot(XX, softReg.coef_[1, :].T)
Z2 = coeffs[2] + np.dot(XX, softReg.coef_[2, :].T)

In [26]:
# probability
P0 = np.exp(Z0)/ (np.exp(Z0)+np.exp(Z1)+np.exp(Z2))
P1 = np.exp(Z1)/ (np.exp(Z0)+np.exp(Z1)+np.exp(Z2))
P2 = np.exp(Z2)/ (np.exp(Z0)+np.exp(Z1)+np.exp(Z2))
# [P0, P1, P2] # highest probability

In [17]:
P0 = np.exp(Z0)/ (np.exp(Z0)+np.exp(Z1)+np.exp(Z2))
P1 = np.exp(Z1)/ (np.exp(Z0)+np.exp(Z1)+np.exp(Z2))
P2 = np.exp(Z2)/ (np.exp(Z0)+np.exp(Z1)+np.exp(Z2))
myyhat = np.array([P0, P1, P2])

In [49]:
myyhat.shape

(3, 944)

In [50]:
myyhat_class = np.argmax(myyhat, axis=0)
myyhat_class.shape

(944,)

In [51]:
yhat = softReg.predict(XX) # prediction
yhat.shape

(944,)

In [53]:
np.mean(myyhat_class==yhat)

1.0

Q1: Calculate $(P_0^{(0)}, P_1^{(0)}, P_2^{(0)})$

Q2: What is your preediction of the 0-th person?