In [1]:
import numpy as np # linear algebra
#import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
#import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression

In [2]:
from numpy import genfromtxt
X = genfromtxt('X_multi.csv', delimiter=',',skip_header=1)
y = genfromtxt('y_multi.csv', delimiter=',',skip_header=1) # class

In [3]:
type(y)

numpy.ndarray

In [4]:
y.shape

(944,)

In [5]:
X.shape

(944, 3)

In [6]:
yy = y.astype(int) # 형변환 float-> int

In [7]:
y_onehot = np.zeros((yy.size, yy.max()+1))
y_onehot[np.arange(yy.size),yy] = 1 # frankly speaking,

In [8]:
y_onehot

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [9]:
y_onehot.shape

(944, 3)

In [12]:
XX=X[:, 1:3]

In [19]:
softReg = LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs')
softReg.fit(X,y)

LogisticRegression(multi_class='multinomial')

In [20]:
softReg.intercept_

array([ 0.78057082, -0.4061704 , -0.37440043])

In [21]:
softReg.coef_

array([[ 7.35712839e-05, -1.45135933e-03, -1.13317374e-02],
       [-3.35892104e-04, -1.22900047e-03,  4.79447948e-03],
       [ 2.62320821e-04,  2.68035980e-03,  6.53725791e-03]])

In [14]:
softReg2 = LogisticRegression(multi_class = 'multinomial', solver = 'lbfgs')
softReg2.fit(XX,yy) #yy : not one-hot encoded

LogisticRegression(multi_class='multinomial')

In [17]:
softReg2.intercept_

array([ 0.78064075, -0.406528  , -0.37411275])

In [18]:
softReg2.coef_

array([[-0.00145259, -0.01133095],
       [-0.00122703,  0.00479373],
       [ 0.00267962,  0.00653722]])

In [22]:
coeffs=softReg2.intercept_

In [11]:
yhat = softReg.predict(X)
np.sum(y == yhat)/len(y)

0.4639830508474576

In [12]:
yhat

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [104]:
temp = np.exp(np.dot(X, softReg.coef_.T )+softReg.intercept_)

In [105]:
temp_sum = np.reshape(np.sum(temp, axis=1), newshape=[944, 1])

In [107]:
prob = temp/temp_sum
prob

array([[0.59148191, 0.18635895, 0.22215914],
       [0.60041202, 0.18850074, 0.21108724],
       [0.59820743, 0.18797572, 0.21381685],
       ...,
       [0.16931722, 0.3331856 , 0.49749718],
       [0.16823592, 0.33127872, 0.50048536],
       [0.16284477, 0.32173414, 0.51542109]])

In [109]:
my_yhat = np.argmax(prob, axis=1)

In [110]:
np.sum(yhat == my_yhat)

944